version: "3.5"
services:
    client:
        build:
          context: ./client
          dockerfile: Dockerfile
        restart: always
        container_name: ether-${ENVIRONMENT}-client
        depends_on:
            - api
        environment:
          PORT: ${CLIENT_PORT}
        ports:
            - ${CLIENT_PORT}:${CLIENT_PORT}
        working_dir: /client/src/app
    api:
        build:
          context: ./api
          dockerfile: Dockerfile
        restart: always
        container_name: ether-${ENVIRONMENT}-api
        depends_on:
            - mongodb
        environment:
          PORT: ${API_PORT}
          DB: mongodb:${DB_PORT}/ether-${ENVIRONMENT}
          DB_USERNAME: ${MONGODB_USERNAME}
          DB_PASSWORD: ${MONGODB_PASSWORD}
          ENVIRONMENT: ${ENVIRONMENT}
        ports:
            - ${API_PORT}:${API_PORT}
    mongodb:
        image: bitnami/mongodb:latest
        restart: always
        container_name: ether-${ENVIRONMENT}-db
        environment:
            MONGODB_PRIMARY_ROOT_PASSWORD: ${MONGODB_PRIMARY_ROOT_PASSWORD}
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_DATABASE: ether-${ENVIRONMENT}
            MONGODB_PORT_NUMBER: ${DB_PORT}
        volumes:
            - ./data-node:/data/db
        ports:
            - ${DB_PORT}
